# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ML-Derkach-Sydorova' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ML-Derkach-Sydorova
pod 'GoogleMLKit/ObjectDetection', '3.2.0'
pod 'GoogleMLKit/ObjectDetectionCustom', '3.2.0'
pod 'GoogleMLKit/ImageLabelingCustom', '3.2.0'
pod 'GoogleMLKit/LinkFirebase', '3.2.0'
pod 'Firebase/MLModelDownloader'
pod 'TensorFlowLiteSwift'

  target 'ML-Derkach-SydorovaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ML-Derkach-SydorovaUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
